### ISSUE TITLE
[shopkeeper] Use Billable Model that is not User

### ISSUE THREAD

**Issue by khongten001** [FriendsOfAdonis/FriendsOfAdonis#14]
Hi there,

Thank you for making Shopkeeper! It is wonderful project.

I have issue when using. In my application, I use `customer` instead of `User`. when saving Subscription the app throws an error because it can't find customerId property (because you hard coded `userId` and `user` on `Subscription` model).

Here is the error:

```
"Customer.subscriptions" expects "customerId" to exist on "Subscription" model, but is missing 
```

Is there any chance to support this?

Thanks!

Sorry for my bad English!

**Comment by kerwanp** [comment]
Hi @khongten001!

I haven't tested this feature fully yet but you can [provide your own models in the configuration](https://github.com/FriendsOfAdonis/FriendsOfAdonis/blob/main/packages/shopkeeper/src/types.ts#L76-L76).

In your case, simply providing the `Customer` model should be enough. The foreignKey on the `Subscription` schema will still be `userId` but target your own `User` model (Customer). 

---

If you want to change the column name to `customerId` you will have to provide your own `Subscription` model:
```ts
export class MySubscription extends Subscription {
  @column()
  declare customerId: number

  @belongsTo(() => shopkeeper.customerModel, { foreignKey: 'customerId'  })
  declare user: BelongsTo<WithBillable>
}
```

Be aware that this might not work properly as currently the custom model MUST be a `Subscription`. In the future it should be a `BaseSubscription` that does not depends on Lucid so you can bring a complete custom Subscription model

**Comment by khongten001** [comment]
Thank you for your reply. I will try and let your know the result!

**Comment by 0xtlt** [comment]
Hi @khongten001, did you make it?
I can't make my custom Subscription model working with typescript :/

**Comment by khongten001** [comment]
Hi @0xtlt 

Try this:

```typescript

import { default as BaseSubscription } from '@foadonis/shopkeeper/models/subscription'
import { column } from '@adonisjs/lucid/orm'

export default class Subscription extends BaseSubscription {
  @column({
    columnName: 'user_id',
  })
  declare stripeServiceId: number
}
// Hack: do Shopkeeper dùng model Subscription gốc nên ko có stripeServiceId
BaseSubscription.$addColumn('stripeServiceId', {
  columnName: 'user_id'
})

```
