### ISSUE TITLE
[graphql] The resolvers array is empty 

### ISSUE THREAD

**Issue by ajagsantiago** [FriendsOfAdonis/FriendsOfAdonis#15]
After installing the package, I need to manually change this provider in `adonisrc.ts`.
`() => import('@foadonis/graphql/graphql_provider')` to 
`() => import('@foadonis/graphql/providers/graphql_provider')`

Also, when starting the application,  it says that:

`Error: Empty 'resolvers' array property found in 'buildSchema' options!`

Even though I have registered the resolver here.

```
import graphql from '@foadonis/graphql/services/main'

graphql.resolvers([() => import('#graphql/resolvers/user_resolver')])
```

**Comment by primotera** [comment]
> After installing the package, I need to manually change this provider in `adonisrc.ts`. `() => import('@foadonis/graphql/graphql_provider')` to `() => import('@foadonis/graphql/providers/graphql_provider')`
> 
> Also, when starting the application, it says that:
> 
> `Error: Empty 'resolvers' array property found in 'buildSchema' options!`
> 
> Even though I have registered the resolver here.
> 
> ```
> import graphql from '@foadonis/graphql/services/main'
> 
> graphql.resolvers([() => import('#graphql/resolvers/user_resolver')])
> ```

Facing the same issue.

**Comment by primotera** [comment]
> > After installing the package, I need to manually change this provider in `adonisrc.ts`. `() => import('@foadonis/graphql/graphql_provider')` to `() => import('@foadonis/graphql/providers/graphql_provider')`
> > Also, when starting the application, it says that:
> > `Error: Empty 'resolvers' array property found in 'buildSchema' options!`
> > Even though I have registered the resolver here.
> > ```
> > import graphql from '@foadonis/graphql/services/main'
> > 
> > graphql.resolvers([() => import('#graphql/resolvers/user_resolver')])
> > ```
> 
 Facing the same issue. and getting the message tried to access Apollo Server when not initialized
when requesting on the navigator /graphql

**Comment by ajagsantiago** [comment]
I have resolve the issue here. The `start/graphql.ts` must be created by using the command `node ace make:preload graphql` or manually add `() => import('#start/graphql')` under preloads in `adonisrc.ts`

**Comment by primotera** [comment]
Thanks @ajagsantiago,
But after adding the start/graphql 
I am facing this new problem.
 TypeError: Cannot read properties of
   undefined (reading 'resolvers')
`
import graphql from '@foadonis/graphql/services/main'

graphql.resolvers([() => import('#graphql/resolvers/user_resolver')])

*
TypeError: Cannot read properties of
   undefined (reading 'resolvers')
*
`
