### ISSUE TITLE
Install error for OpenAPI package

### ISSUE THREAD

**Issue by maxencebonamy** [FriendsOfAdonis/FriendsOfAdonis#5]
When I run the installation command, the following error appears in the terminal:

![Capture d’écran 2024-11-11 à 13 43 28](https://github.com/user-attachments/assets/42d35b86-5d65-4422-940b-77dfac8bff2b)

I tried to install manually using `pnpm`, and it still does not work.
Actually when I do that, the provider is not recognized in the `adonisrc.ts` file, so I looked at the node_modules and there is no build folder in it.

![Capture d’écran 2024-11-11 à 13 45 34](https://github.com/user-attachments/assets/4e299a3c-57bb-43c9-9b32-1784d9b6469e)

**Comment by kerwanp** [comment]
Hey, it seems that there was an issue with the changeset action, this has been fixed!
